IF EXISTS (SELECT * FROM BSDW_2.INFORMATION_SCHEMA.TABLES WHERE table_name = 'STUDENT_ACAD_CRED' and table_schema = 'dbo')
DROP TABLE BSDW_2.dbo.[STUDENT_ACAD_CRED];
GO

 SELECT A.STUDENT_ACAD_CRED_ID
       ,A.PERSON_ID
	   ,A.TITLE
	   ,A.ACAD_LEVEL
	   ,A.COURSE_LEVEL
	   ,A.COURSE_NAME AS STC_COURSE_NAME
	   ,A.SECTION AS STC_SECTION
	   ,A.TERM AS STC_TERM
	   ,CASE WHEN A.REG_CRED IS NULL THEN 0 ELSE A.REG_CRED END AS REG_CRED
	   ,CASE WHEN A.CMPL_CRED IS NULL THEN 0 ELSE A.CMPL_CRED END AS CMPL_CRED
	   ,A.CUM_ATT_CRED
	   ,A.CUM_CMPLT_CRED
	   ,A.CUM_GPA_CRED
	   ,A.ALT_CUM_ATT_CRED
	   ,A.ALT_CUM_CMPL_CRED
	   ,A.ALT_CUM_GPA_CRED
	   ,A.GRADE_POINTS
	   ,A.CUM_CONTRIB_GRADE_POINTS
	   ,A.ALT_CUM_CONTRIB_GRADE_POINTS
	   ,CASE WHEN A.ATT_CRED IS NULL THEN 0 ELSE A.ATT_CRED END AS ATT_CRED
	   ,CASE WHEN A.GPA_CRED IS NULL THEN 0 ELSE A.GPA_CRED END AS GPA_CRED
	   ,C.GRADE
	   ,C.LEGEND
	   ,CASE WHEN C.GRADE_VALUE IS NULL THEN 0 ELSE C.GRADE_VALUE END AS GRADE_VALUE
	   ,A.MARK
	   ,A.MARK_DATE
	   ,A.REPLACED_CODE
       ,B.STATUS_CD
	   ,D.[EXTERNAL_REPRESENTATION] AS STATUS_CD_DESC
	   ,A.CRED_TYPE
	   ,CAST(B.STATUS_DATETIME AS DATE ) AS 'STATUS_DATE'
	   ,GETDATE() AS LASTUPDATE
 INTO BSDW_2.DBO.STUDENT_ACAD_CRED
 FROM COLLIVE.DBO.STUDENT_ACAD_CRED AS A 
 LEFT JOIN 
 COLLIVE.DBO.STUDENT_ACAD_CRED_STATUSES AS B
 ON A.STUDENT_ACAD_CRED_ID = B.STUDENT_ACAD_CRED_ID 
 AND POS  = 1
 LEFT JOIN
 COLLIVE.DBO.GRADES AS C
 ON A.VRFD_GRADE = C.GRADE_ID
 INNER JOIN
 ( SELECT *
 FROM
 [COLLIVE].[dbo].[VALCODES_VALS] 
 WHERE VALCODE_ID = 'STUDENT.ACAD.CRED.STATUSES')AS D
 ON B.STATUS_CD = D.INTERNAL_CODE